// App-wide constants
export const APP_CONFIG = {
  name: "CampusConnect",
  version: "1.0.0",
  description: "Nigeria's Trusted University Marketplace",
  supportEmail: "support@campusconnect.ng",
} as const;

// Debug: Log the Paystack key being used
console.log(
  "Paystack Key:",
  import.meta.env.VITE_PAYSTACK_PUBLIC_KEY
    ? "LIVE KEY LOADED"
    : "USING TEST FALLBACK"
);

export const API_CONFIG = {
  paystack: {
    publicKey: import.meta.env.VITE_PAYSTACK_PUBLIC_KEY,
  },
  supabase: {
    storageUrl:
      import.meta.env.VITE_SUPABASE_STORAGE_URL ||
      "https://ssqplkrxtrvfptrsnpow.supabase.co/storage/v1/object/public",
  },
} as const;

export const BUSINESS_RULES = {
  commission: {
    rate: 0.0, // 0% - No commission, sellers pay registration fee instead
    minAmount: 100, // ₦100
  },
  sellerRegistration: {
    fee: 1000, // ₦1000 first month's subscription fee for sellers
  },
  sellerSubscription: {
    monthlyFee: 1000, // ₦1000 monthly subscription fee for sellers
  },
  escrow: {
    autoReleaseDays: 2,
    disputeWindowDays: 14,
  },
  delivery: {
    flatRate: 0, // ₦2,000
  },
  pagination: {
    defaultLimit: (navigator as any).deviceMemory < 2 ? 10 : 20,
    maxLimit: (navigator as any).deviceMemory < 2 ? 50 : 100,
  },
} as const;

export const UI_CONFIG = {
  breakpoints: {
    sm: 640,
    md: 768,
    lg: 1024,
    xl: 1280,
  },
  animations: {
    fast: 150,
    normal: 300,
    slow: 500,
  },
} as const;

export const ROUTES = {
  home: "/",
  auth: "/auth",
  marketplace: "/marketplace",
  profile: "/profile",
  orders: "/orders",
  cart: "/cart",
  checkout: "/checkout",
  admin: "/admin",
  sell: "/sell",
  dashboard: "/dashboard",
  games: "/games",
} as const;

export const CATEGORIES = [
  {
    id: "books-textbooks",
    name: "Books & Textbooks",
    icon: "Book",
    keywords: [
      "book",
      "textbook",
      "novel",
      "study",
      "academic",
      "literature",
      "manual",
      "guide",
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    icon: "Laptop",
    keywords: [
      "laptop",
      "phone",
      "computer",
      "tablet",
      "headphone",
      "speaker",
      "charger",
      "gadget",
      "tech",
    ],
  },
  {
    id: "fashion-accessories",
    name: "Fashion & Accessories",
    icon: "Shirt",
    keywords: [
      "clothes",
      "shirt",
      "dress",
      "shoes",
      "bag",
      "watch",
      "jewelry",
      "fashion",
      "style",
    ],
  },
  {
    id: "food-beverages",
    name: "Food & Beverages",
    icon: "Utensils",
    keywords: [
      "food",
      "snack",
      "drink",
      "beverage",
      "meal",
      "lunch",
      "breakfast",
      "dinner",
    ],
  },
  {
    id: "sports-recreation",
    name: "Sports & Recreation",
    icon: "Dumbbell",
    keywords: [
      "sport",
      "fitness",
      "gym",
      "exercise",
      "ball",
      "equipment",
      "recreation",
      "game",
    ],
  },
  {
    id: "home-living",
    name: "Home & Living",
    icon: "Home",
    keywords: [
      "furniture",
      "decor",
      "kitchen",
      "bedroom",
      "living",
      "home",
      "appliance",
      "household",
    ],
  },
  {
    id: "stationery-supplies",
    name: "Stationery & Supplies",
    icon: "PenTool",
    keywords: [
      "pen",
      "pencil",
      "paper",
      "notebook",
      "stationery",
      "supplies",
      "office",
      "writing",
    ],
  },
  {
    id: "cosmetics-skincare",
    name: "Cosmetics & Skincare",
    icon: "Sparkles",
    keywords: [
      "cosmetics",
      "skincare",
      "makeup",
      "beauty",
      "cream",
      "lotion",
      "perfume",
      "lipstick",
      "foundation",
      "serum",
      "moisturizer",
      "cleanser",
    ],
  },
  {
    id: "services",
    name: "Services",
    icon: "Users",
    keywords: [
      "service",
      "tutoring",
      "help",
      "assistance",
      "consultation",
      "repair",
      "maintenance",
    ],
  },
] as const;

export const CAMPUSES = [
  { id: "main_campus", name: "Main Campus" },
  { id: "akoka_campus", name: "Akoka Campus" },
  { id: "yaba_campus", name: "Yaba Campus" },
  { id: "distance_learning", name: "Distance Learning" },
] as const;

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export const NIGERIAN_UNIVERSITIES = [
  "Abia State University",
  "Abubakar Tafawa Balewa University",
  "Achievers University",
  "Adamawa State University",
  "Adekunle Ajasin University",
  "Adeleke University",
  "Ahmadu Bello University",
  "Ajayi Crowther University",
  "Akwa Ibom State University",
  "Al-Hikmah University",
  "Al-Qalam University",
  "American University of Nigeria",
  "Anchor University",
  "Anambra State University",
  "Arthur Javis University",
  "Atiba University",
  "Augustine University",
  "Babcock University",
  "Baze University",
  "Bayero University Kano",
  "Bells University of Technology",
  "Benson Idahosa University",
  "Bingham University",
  "Bowen University",
  "Caleb University",
  "Caritas University",
  "Chrisland University",
  "Christopher University",
  "Clifford University",
  "Coal City University",
  "Covenant University",
  "Crawford University",
  "Crescent University",
  "Cross River State University of Technology",
  "Delta State University",
  "Eastern Palm University",
  "Ebonyi State University",
  "Edo University",
  "Edwin Clark University",
  "Ekiti State University",
  "Elizade University",
  "Enugu State University of Science and Technology",
  "Evangel University",
  "Federal University Gashua",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Makurdi",
  "Federal University of Petroleum Resources",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Fountain University",
  "Godfrey Okoye University",
  "Gombe State University",
  "Gregory University",
  "Hallmark University",
  "Hezekiah University",
  "Ibrahim Badamasi Babangida University",
  "Igbinedion University",
  "Imo State University",
  "Joseph Ayo Babalola University",
  "Kaduna State University",
  "Kano University of Science and Technology",
  "Kebbi State University of Science and Technology",
  "Kogi State University",
  "Kwara State University",
  "Ladoke Akintola University of Technology",
  "Lagos State University",
  "Landmark University",
  "Lead City University",
  "Madonna University",
  "McPherson University",
  "Michael Okpara University of Agriculture",
  "Modibbo Adama University of Technology",
  "Mountain Top University",
  "Nasarawa State University",
  "Niger Delta University",
  "Nile University of Nigeria",
  "Nnamdi Azikiwe University",
  "Novena University",
  "Obafemi Awolowo University",
  "Obong University",
  "Oduduwa University",
  "Olabisi Onabanjo University",
  "Osun State University",
  "Pan-Atlantic University",
  "Paul University",
  "Plateau State University",
  "Redeemer's University",
  "Renaissance University",
  "Rhema University",
  "Rivers State University",
  "Salem University",
  "Samuel Adegboyega University",
  "Sokoto State University",
  "Summit University",
  "Taraba State University",
  "The Technical University",
  "Tansian University",
  "University of Abuja",
  "University of Agriculture, Abeokuta",
  "University of Benin",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Nigeria, Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Veritas University",
  "Wesley University",
  "Western Delta University",
  "Yobe State University",
  "Yusuf Maitama Sule University",
] as const;
